### ISSUE TITLE
I want to be able to perform actions on a select set of people

### ISSUE THREAD

**Issue by Data-Officer-BRFC** [Data-Officer-BRFC/Sportmember#15]
I want to be able to move people into teams in one go. For example - I want all senior members to be part of the Social/Parents Team. So I can select everyone above the age of 18 and then move them into the Team. At the moment I only seem to be able to select a team and then perform a bulk action.

**Comment by ThomasSportMember** [comment]
In the members list, you can just use the filter, and only show the ones about 18. Then select all of them, and then edit them all, and put them on the Social/Parents team :)

**Comment by Data-Officer-BRFC** [comment]
OK - I can do this now - just need to remember.

Thanks
