### ISSUE TITLE
Cant seem to write in the predefined Coaches or Team Chat - within the Teams section.

### ISSUE THREAD

**Issue by Data-Officer-BRFC** [Data-Officer-BRFC/Sportmember#17]
Not sure if I am missing something but there is no way to post a chat. If I create a new chat stream then you can post. I have tried in the U14s and the U16s section.

**Comment by Data-Officer-BRFC** [comment]
You need to be a member Player/Coach/Parent to chat in the group - not just an administrative relationship.

**Comment by ThomasSportMember** [comment]
Yeah, you'll need to be part of the team, to chat with the team members.
